[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "connect-src 'self' https://api.staffly.space https://api.api.staffly.space https://api.staffly.space https://nominatim.openstreetmap.org 'unsafe-inline'; img-src 'self' data: https://api.staffly.space https://api.api.staffly.space https://api.staffly.space https://nominatim.openstreetmap.org"
    Referrer-Policy = "no-referrer-when-downgrade"


[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/*.css"
  [headers.values]
    Content-Type = "text/css"

[[headers]]
  for = "/*.json"
  [headers.values]
    Content-Type = "application/json"

[[redirects]]
  from = "https://stafflyhrms.netlify.app/*"
  to = "https://www.api.staffly.space/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://stafflyhrms.netlify.app/*"
  to = "https://www.api.staffly.space/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://stafflytesting.netlify.app/*"
  to = "https://www.api.staffly.space/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://stafflytesting.netlify.app/*"
  to = "https://www.api.staffly.space/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://api.staffly.space/*"
  to = "https://www.api.staffly.space/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://api.staffly.space/*"
  to = "https://www.api.staffly.space/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.api.staffly.space/*"
  to = "https://www.api.staffly.space/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

