import { Chat, ChatMessage, User } from '@/types';

// Mock data for testing the chat feature
export const mockUsers: User[] = [
  {
    id: '1',
    email: 'admin@company.com',
    name: 'Admin User',
    role: 'admin',
    department: 'Management',
    designation: 'System Administrator',
    joiningDate: '2020-01-01',
    status: 'active',
    createdAt: '2020-01-01',
    updatedAt: '2024-01-01',
    // Using placeholder service that works with CORS
    profilePhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=admin&backgroundColor=b6e3f4',
  },
  {
    id: '2',
    email: 'hr@company.com',
    name: 'Sarah Wilson',
    role: 'hr',
    department: 'Human Resources',
    designation: 'HR Manager',
    joiningDate: '2020-02-01',
    status: 'active',
    createdAt: '2020-02-01',
    updatedAt: '2024-01-01',
    profilePhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=sarah&backgroundColor=fecaca',
  },
  {
    id: '3',
    email: 'manager@company.com',
    name: 'Michael Chen',
    role: 'manager',
    department: 'Engineering',
    designation: 'Engineering Manager',
    joiningDate: '2020-03-01',
    status: 'active',
    createdAt: '2020-03-01',
    updatedAt: '2024-01-01',
    profilePhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=michael&backgroundColor=c7d2fe',
  },
  {
    id: '4',
    email: 'teamlead@company.com',
    name: 'Emily Rodriguez',
    role: 'team_lead',
    department: 'Engineering',
    designation: 'Senior Developer',
    joiningDate: '2020-04-01',
    managerId: '3',
    status: 'active',
    createdAt: '2020-04-01',
    updatedAt: '2024-01-01',
    profilePhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=emily&backgroundColor=fed7aa',
  },
  {
    id: '5',
    email: 'employee@company.com',
    name: 'David Johnson',
    role: 'employee',
    department: 'Engineering',
    designation: 'Software Developer',
    joiningDate: '2021-01-01',
    managerId: '3',
    teamLeadId: '4',
    status: 'active',
    createdAt: '2021-01-01',
    updatedAt: '2024-01-01',
    profilePhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=david&backgroundColor=bbf7d0',
  },
];

export const mockChats: Chat[] = [
  {
    id: 'chat-1',
    name: 'Engineering Team',
    type: 'group',
    participants: [
      {
        userId: '1',
        userName: 'Admin User',
        userRole: 'admin',
        department: 'Management',
        joinedAt: '2024-01-01',
        isAdmin: true,
        isOnline: true,
      },
      {
        userId: '2',
        userName: 'Sarah Wilson',
        userRole: 'hr',
        department: 'Human Resources',
        joinedAt: '2024-01-01',
        isAdmin: false,
        isOnline: false,
        lastSeen: '2024-01-15T10:30:00Z',
      },
      {
        userId: '4',
        userName: 'Emily Rodriguez',
        userRole: 'team_lead',
        department: 'Engineering',
        joinedAt: '2024-01-01',
        isAdmin: false,
        isOnline: true,
      },
    ],
    createdBy: '1',
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-15T14:35:00Z',
    unreadCount: 2,
    isActive: true,
    description: 'Engineering team discussions and updates',
    lastMessage: {
      id: 'msg-5',
      chatId: 'chat-1',
      senderId: '4',
      senderName: 'Emily Rodriguez',
      senderRole: 'team_lead',
      senderAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=emily&backgroundColor=fed7aa',
      content: 'Sounds great! I\'ll prepare the agenda and send it to everyone.',
      messageType: 'text',
      timestamp: '2024-01-15T14:35:00Z',
      isRead: false,
    },
  },
  {
    id: 'chat-2',
    name: 'Michael Chen',
    type: 'individual',
    participants: [
      {
        userId: '3',
        userName: 'Michael Chen',
        userRole: 'manager',
        department: 'Engineering',
        joinedAt: '2024-01-01',
        isOnline: true,
      },
    ],
    createdBy: '1',
    createdAt: '2024-01-02T00:00:00Z',
    updatedAt: '2024-01-15T15:00:00Z',
    unreadCount: 1,
    isActive: true,
    lastMessage: {
      id: 'msg-6',
      chatId: 'chat-2',
      senderId: '5',
      senderName: 'David Johnson',
      senderRole: 'employee',
      senderAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=david&backgroundColor=bbf7d0',
      content: 'I\'ve finished the frontend components. Ready for review!',
      messageType: 'text',
      timestamp: '2024-01-15T15:00:00Z',
      isRead: false,
    },
  },
  {
    id: 'chat-3',
    name: 'Sarah Wilson',
    type: 'individual',
    participants: [
      {
        userId: '2',
        userName: 'Sarah Wilson',
        userRole: 'hr',
        department: 'Human Resources',
        joinedAt: '2024-01-01',
        isOnline: false,
        lastSeen: '2024-01-15T10:30:00Z',
      },
    ],
    createdBy: '1',
    createdAt: '2024-01-03T00:00:00Z',
    updatedAt: '2024-01-15T09:00:00Z',
    unreadCount: 0,
    isActive: true,
    lastMessage: {
      id: 'msg-7',
      chatId: 'chat-3',
      senderId: '2',
      senderName: 'Sarah Wilson',
      senderRole: 'hr',
      senderAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=sarah&backgroundColor=fecaca',
      content: 'The new employee onboarding documents are ready for review.',
      messageType: 'text',
      timestamp: '2024-01-15T09:00:00Z',
      isRead: true,
    },
  },
];

export const mockMessages: ChatMessage[] = [
  {
    id: 'msg-1',
    chatId: 'chat-1',
    senderId: '2',
    senderName: 'Sarah Wilson',
    senderRole: 'hr',
    senderAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=sarah&backgroundColor=fecaca',
    content: 'Let\'s schedule the team meeting for next week. I think we should discuss the new project requirements.',
    messageType: 'text',
    timestamp: '2024-01-15T14:30:00Z',
    isRead: false,
  },
  {
    id: 'msg-2',
    chatId: 'chat-2',
    senderId: '1',
    senderName: 'Admin User',
    senderRole: 'admin',
    senderAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=admin&backgroundColor=b6e3f4',
    content: 'Thanks for the update on the project status. Everything looks good!',
    messageType: 'text',
    timestamp: '2024-01-15T12:00:00Z',
    isRead: true,
  },
  {
    id: 'msg-3',
    chatId: 'chat-2',
    senderId: '3',
    senderName: 'Michael Chen',
    senderRole: 'manager',
    senderAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=michael&backgroundColor=c7d2fe',
    content: 'You\'re welcome! The team is making great progress. We should be able to deliver on time.',
    messageType: 'text',
    timestamp: '2024-01-15T11:45:00Z',
    isRead: true,
  },
  {
    id: 'msg-4',
    chatId: 'chat-1',
    senderId: '1',
    senderName: 'Admin User',
    senderRole: 'admin',
    senderAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=admin&backgroundColor=b6e3f4',
    content: '👍',
    messageType: 'emoji',
    timestamp: '2024-01-15T14:25:00Z',
    isRead: true,
  },
  {
    id: 'msg-5',
    chatId: 'chat-1',
    senderId: '4',
    senderName: 'Emily Rodriguez',
    senderRole: 'team_lead',
    senderAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=emily&backgroundColor=fed7aa',
    content: 'Sounds great! I\'ll prepare the agenda and send it to everyone.',
    messageType: 'text',
    timestamp: '2024-01-15T14:35:00Z',
    isRead: false,
  },
  {
    id: 'msg-6',
    chatId: 'chat-2',
    senderId: '5',
    senderName: 'David Johnson',
    senderRole: 'employee',
    senderAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=david&backgroundColor=bbf7d0',
    content: 'I\'ve finished the frontend components. Ready for review!',
    messageType: 'text',
    timestamp: '2024-01-15T15:00:00Z',
    isRead: false,
  },
];